# Generated by Django 3.2.20 on 2023-07-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindingpaws', '0002_auto_20230717_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet_owner_user',
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='minder_name',
            field=models.CharField(blank=True, help_text='This field will be prepopulated on save based on the minder selected', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pet_owner_name',
            field=models.CharField(blank=True, help_text='This field will be prepopulated on save based on the pet owner selected', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minder',
            name='usual_availability',
            field=models.CharField(help_text='Example: Monday to Friday, 10am to 6pm.', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
