# Generated by Django 3.2.20 on 2023-08-15 19:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindingpaws', '0004_auto_20230718_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='minder',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dls3mbdix/image/upload/v1690889814/static/img/profile-placeholder_hgqisr.webp', max_length=255, null=True, verbose_name='image'),
        ),
    ]
